order:
    resource:
        path: ../src/Order/Controller/
        namespace: App\Order\Controller
    type: attribute
shared:
    resource:
        path: ../src/Shared/Controller/
        namespace: App\Shared\Controller
    type: attribute
